### ISSUE TITLE
Clicking Tags in Edit Bookmark closes dialogue

### ISSUE THREAD

**Issue by auxbuss** [BrowserWorks/waterfox#394]
56.0.2
macOS 10.13.2

1. Click on _Edit this Bookmark/Bookmark this Page_ in toolbar (star icon)
2. Click on _Tags_ text field
3. The dialogue closes

It should be possible to type tags into this field. It is possible to edit tags in _Show All Bookmarks_.

**Comment by grahamperrin** [comment]
Not reproducible with 56.0.3_2 on FreeBSD-CURRENT. 

Not reproducible with 56.0.3 on build 16G1210 of Mac OS X 10.12.6.

**Comment by grahamperrin** [comment]
Not reproducible with: 

- 56.0.3_2 on FreeBSD-CURRENT
-  56.0.3 on build 16G1210 of Mac OS X 10.12.6
- 56.0.3 on build 17D25b of Mac OS X 10.13.3 (OS update in progress). 

@auxbuss for you, is the issue reproducible with Waterfox in safe mode?

**Comment by auxbuss** [comment]
It's not reproducible in safe mode. However, if I disable all add-ons (five of), the problem persists.

**Comment by grahamperrin** [comment]
Thanks, can you share troubleshooting information? Copied from `about:support`

Also: if you use a `userChrome.css` file, the content of that file.

**Comment by auxbuss** [comment]
[about:support](https://github.com/MrAlex94/Waterfox/files/1648680/about-config.txt)

`userChrome.css`:
```css
/* Tab bar below Navigation & Bookmarks Toolbars

  For best results, show Title Bar or Menu Bar */
  #nav-bar { /* main toolbar */
  -moz-box-ordinal-group: 1 !important;
  border-top-width: 0 !important;
   }
    #PersonalToolbar { /* bookmarks toolbar */
   -moz-box-ordinal-group: 2 !important;
   }
   #TabsToolbar { /* tab bar */
 -moz-box-ordinal-group: 3 !important;
   }
```
